name: Test and Release
on: [push]

jobs:
  test-and-release:
    name: Run tests and release
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: '9.10.0'
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm run semantic-release
